$.global.AVA_MOGRT_JOB_ID = "ava-cover-pool-02-b90e28b790973378";
$.global.AVA_MOGRT_OUTPUT_FOLDER = "/Users/louislee/Desktop/Adobe_Plugin/templates/premiere/pool";
$.global.AVA_MOGRT_PROJECT = "/Users/louislee/Desktop/Adobe_Plugin/templates/premiere/pool/.build/psu-cover-text-slot-02-generator.aep";
$.global.AVA_MOGRT_RECEIPT = "/Users/louislee/Desktop/Adobe_Plugin/templates/premiere/pool/.build/psu-cover-text-slot-02-project-receipt.json";
$.global.AVA_MOGRT_TEMPLATE_NAME = "psu-cover-text-slot-02";
$.global.AVA_MOGRT_PERSON_NAME = "ชื่อ นามสกุล";
$.global.AVA_MOGRT_POSITION_TITLE = "ตำแหน่ง / หน่วยงาน";
$.global.AVA_MOGRT_AWARD = "รางวัลหรือเกียรติคุณ";
$.global.AVA_MOGRT_PROJECT_ONLY = true;
$.global.AVA_MOGRT_QUIT_AFTER_PROJECT = true;
$.evalFile(File("/Users/louislee/Desktop/Adobe_Plugin/adobe/after-effects/create-cover-text-mogrt.jsx"));
